owner: Mid0aria
repo: anlayana-uptime

sites:
  - name: Anlayana
    url: https://anlayana.com
  - name: Mido
    url: https://mido.anlayana.com
  - name: Syan
    url: https://syan.anlayana.com    
  - name: Cards
    url: https://cards.anlayana.com  

status-website:
  cname: uptime.anlayana.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Anlayana Uptime
  introTitle: "Anlayana"
  introMessage: The uptime of all systems under anlayana.com
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
